### ISSUE TITLE
Rename to libitk

### ISSUE THREAD

**Issue by thewtex** [conda-forge/libitk-feedstock#8]
Since this package just provides the C++ headers / libraries, it could be renamed to `libitk`, which would be consistent libxml2, libdap4, libiconv, libtiff, etc., and would facilitate installation of the [Python bindings package](https://github.com/conda-forge/staged-recipes/pull/3263) with `conda install itk`.

**Comment by blowekamp** [comment]
This is a sensible request. I am not sure how that can be done with in the condo-forge infrastructure and how best to mange the compatibility issue with the couple packages currently depending on "itk" for the libraries....

**Comment by thewtex** [comment]
@jjhelmus @msarahan @ericdill any ideas on how to proceed?

**Comment by ericdill** [comment]
The mechanism here would be to 

1. update the recipe name to be "libitk" instead of "itk"
1. rebuild libitk packages
1. update all downstream dependencies to pull in libitk instead of itk
1. rename this repository to libitk-feedstock (need's conda-forge admin)
1. move all itk packages to the "broken" label on anaconda.org/conda-forge (needs conda-forge admin)
1. Merge https://github.com/conda-forge/staged-recipes/pull/3263 which will create a new itk-feedstock (needs staged-recipes committer)

**Comment by thewtex** [comment]
@ericdill Sounds like a very good plan.

This PR: https://github.com/conda-forge/itk-feedstock/pull/9 should address 1). 

Merging should address 2).

I'll search for downstream packages, but any tips will be appreciated.

**Comment by thewtex** [comment]
A GitHub search of the conda-forge organization did not reveal any current dependencies.

**Comment by ericdill** [comment]
> I'll search for downstream packages, but any tips will be appreciated.

@thewtex I looked through anaconda.org/conda-forge for linux-64, win-64 and osx-64 (programmatically) and didn't find any packages

**Comment by blowekamp** [comment]
I believe the renaming have been successfully completed. The old itk package has disappeared from anaconda.org.
